name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Install dependencies
      run: 
        yarn install --production=true --pure-lockfile
        yarn add turbo@1.13.3 typescript@5.4.5 jest@29.5.0 ts-jest@29.1.0"

    - name: Build
      run: yarn build

    - name: Run tests
      run: yarn test